### PR TITLE
disable ssh key replacement

### PR DESCRIPTION
**Pull request by novemberborn**
Vagrant 1.7.0 changed behavior to always replace the default key, which then breaks SSH access to the box.

### CODE REVIEW

**Comment by vaijab** [comment]
@novemberborn does it break ssh access to an existing box?

**Comment by novemberborn** [comment]
@vaijab yea, because it's not selecting the right key or something.

**Comment by vaijab** [comment]
I guess we could check whether a box already exists, if not let vagrant behave as it should.

**Comment by danharvey** [comment]
Does this not break it for new instances?

**Comment by novemberborn** [comment]
It only replaces the default key at the next boot. See <https://github.com/mitchellh/vagrant/pull/4707>.

**Pull request merged**
