### PR TITLE
expose etcd api port

### PR DESCRIPTION
**Pull request by vaijab**

### CODE REVIEW

**Comment by danharvey** [comment]
Why?

Just use the host only network. Going via the NAT interface is a bad idea.

**Comment by danharvey** [comment]
I personally think we should also remove the docker port forward to unconfuse people that using that is a good idea.

**Comment by vaijab** [comment]
> Going via the NAT interface is a bad idea.

Why is it a bad idea?

**Comment by danharvey** [comment]
It's slow, buggy, and seems to just stop working now and again.

**Comment by vaijab** [comment]
> It's slow, buggy, and seems to just stop working now and again.

That could be an OS X thing. I have never had issues on linux. Anyway, I am happy this to be closed.

**Pull request closed without merging**
